name: Feltes
description: A new Flutter project.
version: 1.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  flutter_spinkit: ^4.1.0
  url_launcher: ^5.2.7
  font_awesome_flutter: ^8.5.0
  modal_progress_hud: ^0.1.3
  provider: ^3.2.0
  firebase_auth: ^0.15.2
  cloud_functions: ^0.4.1+6
  firebase_storage: ^3.1.1
  image_picker: ^0.6.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
